### ISSUE TITLE
Stack traces in non-exception log events

### ISSUE THREAD

**Issue by TamasSzigeti** [B-Galati/monolog-sentry-handler#18]
Hi,
thanks for this wrapper.

It seems that the insides of sentry is designed in a way that it is nearly impossible to get stack traces for regular monolog events (non-exceptions), unless we are using captureMessage instead of captureEvent.

Any idea how to implement this?

**Comment by TamasSzigeti** [comment]
Sorry I realised this issue belongs to the core package instead
https://github.com/getsentry/sentry-php/issues/939

**Comment by B-Galati** [comment]
Thank you!
