### ISSUE TITLE
Bundle?

### ISSUE THREAD

**Issue by temp** [B-Galati/monolog-sentry-handler#19]
Thanks for your great work! 

Have you ever considered bundling your config from the symfony-guide into a bundle?
We are using it the factory code 1:1, and have placed it in a bundle with some configurations, and with configurable listeners (for console, request, user). 
Works like a charm.

**Comment by B-Galati** [comment]
Thanks for your feedback! Really appreciate it!

I have considered doing a bundle with but I am running out of time these days.

Actually it's possible to use the official symfony bundle now that it is allowed to disable the exception listener but it would not be as customizable of course. Also, I still need to check if it  could do everything the symfony guide do in a reasonable way.

Would you be interested to share the bundle you did? I could set up a private repo and we could then work the details out of it.

**Comment by temp** [comment]
Yes, I will move the bundle from our private gitlab to github soon, will leave a message here. Might take a few days, since I'm not able to work right now.

**Comment by temp** [comment]
Sorry for the delay, this corona-stuff is really messing with my ability to do extra-work ;-)
Nevertheless, I put my variant here: https://github.com/temp/sentry-bundle
Hope that the work in https://github.com/getsentry/sentry-symfony/issues/337 will make this unncessary!

**Comment by B-Galati** [comment]
Thanks!

**Comment by antishov** [comment]
Any updates here?

**Comment by B-Galati** [comment]
The official Sentry Bundle should adopt the behavior describe in the next major. see https://github.com/getsentry/sentry-symfony/issues/337

**Comment by B-Galati** [comment]
Closing as this is gonna be fixed in the official Sentry Symfony bundle
