### ISSUE TITLE
High logging level results in Null error

### ISSUE THREAD

**Issue by Heinzelhe** [B-Galati/monolog-sentry-handler#21]
[patch.txt](https://github.com/B-Galati/monolog-sentry-handler/files/5056635/patch.txt)

Setting the error level to 500 results in the following error;

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Monolog\Handler\AbstractProcessingHandler::handle() must be of the type array, null given, called in /var/www/api/vendor/bgalati/monolog-sentry-handler/src/SentryHandler.php on line 71 and defined in /var/www/api/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:29

**Comment by B-Galati** [comment]
Thanks @Heinzelhe I will check it out whenever I can

**Comment by B-Galati** [comment]
Now fixed in 1.2.2

Thanks a lot for opening this issue :+1:
