### ISSUE TITLE
Support for sentry/sdk:^3.0

### ISSUE THREAD

**Issue by radimvaculik** [B-Galati/monolog-sentry-handler#23]
There is a new major version of Sentry SDK for PHP.

See upgrade docs https://github.com/getsentry/sentry-php/blob/master/UPGRADE-3.0.md

**Comment by B-Galati** [comment]
I saw. Thanks for the heads up.

**Comment by radimvaculik** [comment]
@B-Galati Any update? Thanks!

**Comment by B-Galati** [comment]
Will try to tackle it asap!

**Comment by allan-simon** [comment]
Hello, any update on this or anyway one can help ? as it's the single one dependency that refrain me from upgrading to php8 :)

**Comment by B-Galati** [comment]
@allan-simon #25 is tackling this issue but it's not on my priority list for the moment.

**Comment by radimvaculik** [comment]
There is official Monolog handler for Sentry already. https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php

**Comment by B-Galati** [comment]
@radimvaculik read my FAQ, the handler does not manage breadcrumbs ;-) 

https://github.com/B-Galati/monolog-sentry-handler#what-are-the-differences-with-the-official-monolog-sentry-handler

**Comment by B-Galati** [comment]
Fix by #25
