### ISSUE TITLE
sentry/sentry 4.x

### ISSUE THREAD

**Issue by temp** [B-Galati/monolog-sentry-handler#33]
Hi there!

Will there be a version of the monolog-sentry-handler for sentry/sentry 4.x?
I know that there were discussions about including the functionality of your package in sentry, but I can't remember what the current situation was...

**Comment by B-Galati** [comment]
Hello @temp!

A new version will be released for the v4 for sure. I don't have any ETA yet.

My package won't be included in the official package. I had a light of hope when they added a new Monolog Handler but it does not work like this one sadly. You have more information in the [FAQ](https://github.com/B-Galati/monolog-sentry-handler#what-are-the-differences-with-the-official-monolog-sentry-handlers). 

Let me know if anything is unclear. I'll enrich the FAQ.

**Comment by temp** [comment]
@B-Galati Yes, I can remember the discussion. I'll glady stick to your handler, in my opinion it makes more sense than the official handlers. Thanks for your help!

**Comment by B-Galati** [comment]
Re-open to keep track of the new version of Sentry 👍

**Comment by temp** [comment]
Is it really supporting sentry 4.x? When I install `composer require bgalati/monolog-sentry-handler sentry/sentry-symfony symfony/http-client nyholm/psr7` I only get sentry/sentry 3.x
Is there something missing from the sentry-end? Doesn't the bundle support sentry/sentry 4.x yet?

**Comment by B-Galati** [comment]
@temp

Sadly `sentry/sentry-symfony` does not support Sentry V4 yet.

See https://github.com/getsentry/sentry-symfony/issues/783

**Comment by B-Galati** [comment]
The V4 support has been released in the new bundle version :tada: 

https://github.com/getsentry/sentry-symfony/releases/tag/5.0.0

**Comment by temp** [comment]
Thanks for the hint!
